version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true

  # db:
  #   build: ./infra/mysql
  #   volumes:
  #     - db-store:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - app-net

  db:
    image: mysql:8.0
    volumes:
      - db_store:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Tokyo

volumes:
  db_store: